### ISSUE TITLE
Major Installation Issues

### ISSUE THREAD

**Issue by drphero** [ttchengab/zest_code#3]
I saw your example results and thought they looked really good so I decided to try it out. I have it working now, but it took almost two hours to get it running. 

Let me preface this by saying I just want to see the project improve and to allow anyone to be able to get it running and that I think the work you've done here is very cool. 

Now that being said, every part of the install process has some major problems and missing parts. I will try to list what I remember doing, but I think it would be best for you to try this and see for yourself:

- Create a new clean conda environment (or venv if you prefer), I used python 3.9
- Follow the README instructions line by line without adding or changing anything from it. Just copy/paste.
- Try to run demo_gradio.py

You will see that there are many hurdles.

Okay, now that you have done that, here are the things that I can remember doing:

<details>
  <summary>Spoiler warning</summary>

  - Diffusers version 0.22.1 is not correct, had to use latest diffusers
  - Several missing dependencies, including rembg, einops, transformers, newer opencv-python, gradio, accelerate
  - Told to cd into IP-Adapter directory that was just removed in the previous instruction
  - Cloning IP-Adapter also downloads an 18GB .git folder. I see other models were automatically downloaded from HF, can these also be done that way?
  - Unclear final folder structure
  - DPT installs an extremely old version of torch and not the CUDA version if you're on windows
  - No mention of downloading the required DPT models
  - Gradio demo tries to load DPT weights from DPT/dpt_weights directory, but it should be DPT/weights
  - Specific image dimensions should be used?
  
</details>

**Comment by ttchengab** [comment]
Hi, Thank you very much for addressing this! Apologies, it seems like my conda environment was running weird so it used some additional libraries from other environments that I am not aware of.

I have tried to address most of the concerns but will dive into a deeper look to make sure everything is optimized. Thanks again!
