### ISSUE TITLE
Do IP-adapters require fine-tuning?

### ISSUE THREAD

**Issue by 838959823** [ttchengab/zest_code#7]
After reading the paper, it appears that there is no supervision or constraint on capturing material information from exemplars if the IP adapters are not fine-tuned.

**Comment by ttchengab** [comment]
Hi @838959823 , No the IP-Adaptor does not require fine-tuning.

You are correct -- IP-Adaptor captures all information (geometry, illumination, materials). This is why we would need the two branches -- geometry guidance and latent illumination guidance. We found that depth estimation + ControlNet overwrites the geometry from IP-Adaptor, and foreground decolored image + inpainting overwrites the illumination. Therefore, only the material information is passed down from IP-Adaptor.

This is also why we called it zero-shot material transfer.

Hope this helps!

**Comment by 838959823** [comment]
Thank you for your response. It is very amazing and interesting.
