### ISSUE TITLE
how to add multiple texture in to a single image...

### ISSUE THREAD

**Issue by planetgranito** [ttchengab/zest_code#9]

**Comment by planetgranito** [comment]
This is an excellent piece of work! I appreciate the effort and creativity that went into this project. I have a question regarding the process: how can one add multiple textures into a single image? Any guidance or examples would be greatly appreciated.

**Comment by ttchengab** [comment]
Hi @planetgranito ! 
Thank you for your interest in our work! 

I plan on adding a demo for multi-texture edits later into the current pipeline. For now, here is an overview:
1. Obtain a set of masks from an image using open vocabulary segmentation. I used this: https://github.com/facebookresearch/segment-anything
2. Run Zest Iteratively. That is, apply ZeST using one of the masks, save the image, then use it as the input again to apply the next Texture.

Technically it is possible to attach multiple IP-Adapters using the diffusers library and just apply two masks at the same time, which is something I plan on to add in future releases. For now, the above pipeline should be the most straightforward

You can also find more results and descriptions in Figure 8 and Section 4.5 of our paper: https://arxiv.org/abs/2404.06425

Hope this helps!
